import 'dotenv/config';
import express from 'express';import cors from 'cors';import multer from 'multer';import fs from 'node:fs/promises';import path from 'node:path';import OpenAI from 'openai';
import { inputSchema } from '../schemas/inputSchema';import { generateStoryboard } from '../core/generateStoryboard';import { buildAssetList } from '../core/buildAssetList';import { resolveAssets } from '../core/assetResolver';import { compose } from '../core/mediaComposer';import { buildManifest } from '../core/manifestBuilder';import { writeJson } from '../core/outputWriter';import { validatePastedStoryboard } from '../core/normalizeStoryboard';import { applyValidation, validateImageAsset } from '../core/assetValidation';
const app=express(); app.use(cors()); app.use(express.json({limit:'5mb'})); app.use('/outputs',express.static(path.join(process.cwd(),'outputs'))); const upload=multer({dest:'public/uploads'});
const store=new Map<string,any>(); const settings:{apiKey?:string,model:string}={apiKey:process.env.OPENAI_API_KEY,model:process.env.OPENAI_MODEL||'gpt-4.1-mini'};
const ok=(data:any)=>({ok:true,data}); const err=(m:string,d:any={})=>({ok:false,error:m,details:d}); const mask=(k?:string)=>k?`${k.slice(0,3)}****${k.slice(-4)}`:null;
const mkId=(s:string)=>`${s.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,36)}-${Date.now()}`;
async function bootstrap(project_id:string,storyboard:any,source:string){const dir=path.join('outputs',project_id);await fs.mkdir(path.join(dir,'assets'),{recursive:true});await writeJson(path.join(dir,'storyboard.json'),storyboard);const warnings:string[]=[];let asset_list=buildAssetList(project_id,storyboard);asset_list=await resolveAssets(dir,storyboard,asset_list,warnings);await writeJson(path.join(dir,'asset_list.json'),asset_list);const manifest=buildManifest(project_id,storyboard,asset_list,warnings);await writeJson(path.join(dir,'edit_manifest.json'),manifest);const tdh=storyboard.title_description_hashtags;await fs.writeFile(path.join(dir,'title_description_hashtags.txt'),`TITLE:
${tdh.title}

DESCRIPTION:
${tdh.description}

HASHTAGS:
${tdh.hashtags.join(' ')}`);let c=0;const lines=storyboard.scenes.map((sc:any)=>{const st=c;c+=sc.estimated_duration_sec;return `[${sc.scene_id} | 0:${String(st).padStart(2,'0')} - 0:${String(c).padStart(2,'0')}]\n${sc.voiceover}`;});await fs.writeFile(path.join(dir,'capcut_voiceover_script.txt'),lines.join('\n\n'));const st={project_id,storyboard,asset_list,manifest,warnings,storyboard_source:source,output_paths:{storyboard_json:path.join(dir,'storyboard.json'),asset_list_json:path.join(dir,'asset_list.json'),edit_manifest_json:path.join(dir,'edit_manifest.json'),capcut_voiceover_script:path.join(dir,'capcut_voiceover_script.txt'),title_description_hashtags:path.join(dir,'title_description_hashtags.txt')}};store.set(project_id,st);return st;}
async function persistProject(st:any){const dir=path.join('outputs',st.project_id);st.manifest=buildManifest(st.project_id,st.storyboard,st.asset_list,st.warnings);await writeJson(path.join(dir,'asset_list.json'),st.asset_list);await writeJson(path.join(dir,'edit_manifest.json'),st.manifest);}
app.get('/api/settings',(_q,r)=>r.json(ok({has_openai_api_key:!!settings.apiKey,masked_openai_api_key:mask(settings.apiKey),openai_model:settings.model})));
app.post('/api/settings',(q,r)=>{settings.apiKey=q.body.openai_api_key||settings.apiKey;settings.model=q.body.openai_model||settings.model;r.json(ok({has_openai_api_key:!!settings.apiKey,masked_openai_api_key:mask(settings.apiKey),openai_model:settings.model}));});
app.post('/api/settings/clear-openai-key',(_q,r)=>{settings.apiKey=undefined;r.json(ok({has_openai_api_key:false,masked_openai_api_key:null,openai_model:settings.model}));});
app.post('/api/settings/test-openai',async(_q,r)=>{try{if(!settings.apiKey) return r.status(400).json(err('No OpenAI API key configured')); const c=new OpenAI({apiKey:settings.apiKey}); await c.responses.create({model:settings.model,input:'ping'}); r.json(ok({message:'OpenAI connection successful'}));}catch(e:any){r.status(400).json(err(`OpenAI test failed: ${e.message}`));}});
app.post('/api/storyboard/generate',async(q,r)=>{try{const input=inputSchema.parse(q.body); const g=await generateStoryboard(input,[],{apiKey:settings.apiKey,model:settings.model}); const st=await bootstrap(mkId(input.topic),g.storyboard,g.source); r.json(ok(st));}catch(e:any){r.status(400).json(err(e.message));}});
app.post('/api/storyboard/use-pasted',async(q,r)=>{try{const parsed=validatePastedStoryboard(q.body.storyboard); if(!parsed.ok) return r.status(400).json(err(parsed.errors.join('\n'),{errors:parsed.errors})); const st=await bootstrap(mkId(parsed.storyboard.project_title),parsed.storyboard,'pasted'); r.json(ok(st));}catch(e:any){r.status(400).json(err(e.message));}});
app.post('/api/assets/resolve',async(q,r)=>{const st=store.get(q.body.project_id); if(!st) return r.status(404).json(err('Project not found')); st.asset_list=await resolveAssets(path.join('outputs',st.project_id),st.storyboard,st.asset_list,st.warnings); await persistProject(st); r.json(ok(st));});
app.post('/api/assets/refetch',async(q,r)=>{const st=store.get(q.body.project_id); if(!st) return r.status(404).json(err('Project not found')); const target=st.asset_list.assets.find((a:any)=>a.scene_id===q.body.scene_id); if(!target) return r.status(404).json(err('Asset not found')); await resolveAssets(path.join('outputs',st.project_id),st.storyboard,{project_id:st.project_id,assets:[target]},st.warnings); await persistProject(st); r.json(ok(st));});
app.post('/api/assets/upload',upload.single('file'),async(q,r)=>{const st=store.get(q.body.project_id); if(!st||!q.file) return r.status(400).json(err('Missing data')); const out=path.join('outputs',st.project_id,'assets',`${q.body.scene_id}${path.extname(q.file.originalname)||'.png'}`); await fs.rename(q.file.path,out); const a=st.asset_list.assets.find((x:any)=>x.scene_id===q.body.scene_id); if(!a) return r.status(404).json(err('Asset not found')); a.local_path=out; a.is_placeholder=false;applyValidation(a,await validateImageAsset(out));a.status=a.validation_status==='valid'?'asset_generated':'asset_validation_failed';a.error_message=a.validation_errors.join('; ')||null; await persistProject(st); r.json(ok(st));});
for (const action of ['approve','reject']) app.post(`/api/assets/${action}`,async(q,r)=>{const st=store.get(q.body.project_id); if(!st) return r.status(404).json(err('Project not found')); const a=st.asset_list.assets.find((x:any)=>x.scene_id===q.body.scene_id); if(!a) return r.status(404).json(err('Asset not found')); a.status=action==='approve'?'approved':'rejected'; await persistProject(st); r.json(ok(st));});
app.post('/api/render',async(q,r)=>{try{const st=store.get(q.body.project_id); if(!st) return r.status(404).json(err('Project not found')); const dir=path.join('outputs',st.project_id); await compose(dir,st.storyboard,st.asset_list); r.json(ok(st));}catch(e:any){r.status(500).json(err(`Render failed: ${e.message}`));}});
app.get('/api/project/:projectId',(q,r)=>{const st=store.get(q.params.projectId); if(!st) return r.status(404).json(err('Project not found')); r.json(ok(st));});
app.listen(Number(process.env.PORT||3001));
