import { useEffect, useMemo, useState } from 'react';
const defaults={topic:'BTC returns to 80K: real breakout or leverage trap?',platform:'youtube',aspect_ratio:'16:9',language:'en',target_duration_sec:120,video_type:'crypto_analysis',tone:'sharp, analytical, retention-focused'};
export default function App(){const [form,setForm]=useState(defaults);const [pasted,setPasted]=useState('');const [status,setStatus]=useState('Idle');const [msg,setMsg]=useState('');const [project,setProject]=useState<any>();const [settings,setSettings]=useState<any>({openai_model:'gpt-4.1-mini'});const [apiKey,setApiKey]=useState('');
const req=async(url:string,init?:RequestInit)=>{setStatus('Loading');const r=await fetch(`http://localhost:3001${url}`,init);const j=await r.json();if(!j.ok) throw new Error(j.error);setStatus('Success');setProject(j.data.project_id?j.data:project);return j.data;};
const loadSettings=()=>req('/api/settings').then(d=>setSettings(d)).catch(e=>{setStatus('Error');setMsg(e.message)}); useEffect(()=>{loadSettings();},[]);
const sourceLabel=(s:string)=>s==='openai'?'OpenAI':s==='fallback'?'Fallback':'Pasted JSON';
const gen=()=>req('/api/storyboard/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}).catch(e=>{setStatus('Error');setMsg(e.message)});
const useP=()=>{if(!pasted.trim()) return setMsg('Pasted JSON is empty'); try{const obj=JSON.parse(pasted); req('/api/storyboard/use-pasted',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storyboard:obj})});}catch{setStatus('Error');setMsg('Invalid pasted JSON')}};
const action=(u:string,sid:string)=>req(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:project.project_id,scene_id:sid})}).then(setProject).catch(e=>{setStatus('Error');setMsg(e.message)});
return <div className='page'><h1>CapCut Handoff MVP</h1>
<section><h2>API Settings</h2><p>Configured: {settings.masked_openai_api_key||'No key configured'}</p><input placeholder='OpenAI API Key' value={apiKey} onChange={e=>setApiKey(e.target.value)}/><input value={settings.openai_model||'gpt-4.1-mini'} onChange={e=>setSettings({...settings,openai_model:e.target.value})}/><button onClick={()=>req('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({openai_api_key:apiKey,openai_model:settings.openai_model})}).then(loadSettings)}>Save API Settings</button><button onClick={()=>req('/api/settings/test-openai',{method:'POST'}).then(()=>setMsg('OpenAI test successful')).catch(e=>setMsg(e.message))}>Test API Connection</button><button onClick={()=>req('/api/settings/clear-openai-key',{method:'POST'}).then(loadSettings)}>Clear API Key</button></section>
<section><h2>Input Panel</h2>{Object.entries(form).map(([k,v])=><label key={k}>{k}<input value={String(v)} onChange={e=>setForm({...form,[k]:k==='target_duration_sec'?Number(e.target.value):e.target.value})}/></label>)}<button onClick={gen}>Generate Storyboard</button><textarea rows={8} value={pasted} onChange={e=>setPasted(e.target.value)}/><button onClick={useP}>Use Pasted Storyboard</button></section>
<section><h2>Status / Warnings</h2><div>{status}</div>{msg&&<div className='err'>{msg}</div>}{project?.warnings?.map((w:string)=><div className='warn' key={w}>{w}</div>)}{project&&<div>Storyboard Source: {sourceLabel(project.storyboard_source)}</div>}</section>
{project&&<section><h2>Storyboard Timeline</h2>{project.storyboard.scenes.map((s:any)=>{const a=project.asset_list.assets.find((x:any)=>x.scene_id===s.scene_id);return <article className='card' key={s.scene_id}><h3>{s.scene_id}</h3><p>{s.purpose} | {s.estimated_duration_sec}s | {s.visual_type}</p><p>{s.voiceover}</p><p>{s.on_screen_text}</p><p>Status: {a?.status}</p>{a?.local_path&&<img src={`http://localhost:3001/${String(a.local_path).replace(/^outputs\//,'outputs/')}`}/>}<button onClick={()=>action('/api/assets/approve',s.scene_id)}>Approve Asset</button><button onClick={()=>action('/api/assets/reject',s.scene_id)}>Reject Asset</button><button onClick={()=>action('/api/assets/refetch',s.scene_id)}>Re-fetch Asset</button><input type='file' onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('project_id',project.project_id);fd.append('scene_id',s.scene_id);fd.append('file',f);const r=await fetch('http://localhost:3001/api/assets/upload',{method:'POST',body:fd});const j=await r.json();if(j.ok)setProject(j.data);}}/></article>})}</section>}
{project&&<section><h2>Render Panel</h2><button onClick={()=>req('/api/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:project.project_id})}).then(d=>setProject(d)).catch(e=>{setStatus('Error');setMsg(e.message)})}>Generate Rough Cut</button></section>}
{project&&<section><h2>Output Paths</h2><pre>{JSON.stringify(project.output_paths,null,2)}</pre></section>}</div>}
